ministryofjustice/prisoner-contact-registry

README.md, prisoner-contact-registry-api-specification.yaml
Add API specification
Remove template text from readme
=> Add Draft API specification

build.gradle.kts
=> Gradle log4j update to version 3.3.16

helm_deploy/prisoner-contact-registry/Chart.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/config/AuthAwareTokenConverter.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/utils/UserMdcFilter.kt
Adds the authenticated userId to logs
=> MDC filter for logging user id

src/main/resources/application-dev.yml
Increases the Prison API timeout in DEV
Set a realistic timeout for the environment.
=> Prison API DEV timeout

build.gradle.kts
Upgrades hmpps spring-boot plugin to version 4.0.4
Security scan
=> Upgrade to version 4.0.4

.circleci/config.yml
Disables Circle CI PROD deployment
=> vb-583 disable prod deployment

.circleci/config.yml, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/config/ApplicationInsightsConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/config/ClientTrackingConfiguration.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/config/PrisonerContactRegistryExceptionHandler.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/health/VersionOutputter.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/service/PrisonerContactRegistryServiceTest.kt
Upgrades gradle to 7.4.1
Upgrades hmpps gradle-spring-boot to version 4.1.0
Cleans up imports
=> Upgrade gradle and deps

.trivyignore, build.gradle.kts
=> Upgrade to 4.1.2

Dockerfile, README.md, build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
Resolves trivy scan security failures in build
Prep for promoting into pre-prod
=> VB-616 build config

build.gradle.kts
Upgrade to gradle plugin 4.1.4 for build warnings
=> Upgrade gradle plugin

.circleci/config.yml
removed invalid config from circle config.yml
=> Circle config clean up

build.gradle.kts
=> Redundant dep removed

.circleci/config.yml, helm_deploy/values-staging.yaml
Add CICD configuration for staging envrionment 
Enable microservice images to be configured and pushed into "VSIP-dev" namespace
=> Add CICD configuration for staging envrionment

build.gradle.kts
Upgrade dependencies
Resolve build security warnings
=> VB-666 Upgrade to 4.1.5

.circleci/config.yml, README.md, docker-compose-local.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/config/PrisonerContactRegistryExceptionHandler.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/PrisonerContactControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/mock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/swagger/OpenApiDocsTest.kt, src/test/resources/application-test.yml
Brings Prisoner-Contact-Registry up to date with Visit-Scheduler
Circle CI
Local Env
Test package names & static analysis
Keep the two APIs consistent.
=> VB-693 Update to CI, local env and package names

build.gradle.kts
Upgrades the dps gradle plugin to version 4.1.6
resolves trivy warnings in the build
=> VB-730 upgrade dps plugin to 4.1.6

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
Change subdomain to "prison"
Conform to HMPPS guidelines. Note this will break affected environments. Need to co-ordinate merges to minimise downtime
=> https_/dsdmoj.atlassian.net/browse/VB-775

.circleci/config.yml
Uncomment workflow to deploy to production environment 
commission production environment
=> Production environment commissioning

build.gradle.kts
Upgrade to dps gradle plugin and dependencies for version 4.1.7
Resolve build warnings
=> VB-844 Upgrade dps plugin 4.1.7

build.gradle.kts
Upgrade to dps gradle plugin to version 4.2.0
Resolve build warnings
=> VB-869 DPS gradle plugin upgrade to version 4.2.0

build.gradle.kts
Gradle plugin upgrade to version 4.2.1
=> VB-913 Gradle plugin upgrade to version 4.2.1

.circleci/config.yml, build.gradle.kts
Upgrades dependencies
Resolve build security warnings
=> VB-916 dependencies

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/config/OpenApiConfiguration.kt
Change subdomain in openapi config from hmpps to prison
Make configuration correct and in line with the service
=> https_/dsdmoj.atlassian.net/browse/VB-787_pt2

build.gradle.kts
Upgrade to gradle plugin version 4.3.2
Resolve build security warnings
=> VB-1028 Upgrade to version 4.3.2

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, helm_deploy/prisoner-contact-registry/Chart.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/config/ResourceServerConfiguration.kt
Ensures plugins and dependencies are up to date
to ensure the system is secure
=> VB-1130 Prisoner contact registry : Update plugins and dependencies

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/controller/PrisonerContactController.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/PrisonerContactControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/mock/PrisonApiMockServer.kt
makes sure the contacts are in the correct order (last name, first name)
e.g.
Aled Aeron
Aled Cynog
William Aeron
William Cynog
To fix a defect, when there is no order
=> VB-1138 Alphabetical-ordering-of-visitor-list

build.gradle.kts
update to gradle-spring-boot to version 4.5.0
to keep project up to date with latest dependencies
=> VB-1184-Update-Dependencies-prisoner-contact-registry

.trivyignore, build.gradle.kts
updates dependancies
_Required._
for good security
=> VB-1259 Dependancy update to Prisoner-contact-registry

.trivyignore, build.gradle.kts
Updates dependancies
To improve security and reduce bugs
=> VB-1310 Prisoner-contact-registry - Update dependancies

helm_deploy/values-staging.yaml
adds a values yaml file for the new staging env
to allow us to set values for the new staging env
=> VB-1346 Create a values-staging.yaml

.circleci/config.yml
added staging details to CI config.yml
to instruct circle CI process flow
=> VB-1347 Add staging details to the config.yml

.circleci/config.yml
Correct an error added in the last PR for config changes for staging
allows the process to be approved properly
=> VB-1347 Add staging details to the config defect

.circleci/config.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/config/OpenApiConfiguration.kt
fixing up build issues for new staging env
defect need to be fixed to allow new staging env
=> VB-1347 Add staging details to the config defect 2

.circleci/config.yml, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/config/OpenApiConfiguration.kt
fix a CI config issue wrong context name
to allow us to release to staging
=> Vb 1347 add staging details to the config, defect 2

build.gradle.kts
Update of dependancies
ensure latest fixes to third party dependancies
=> VB-1364 Prisoner-contact-registry - Update dependancies

build.gradle.kts
Update hmpps.gradle-spring-boot dependency to 4.5.7
Fix security issues reported by build process.
=> Update hmpps.gradle-spring-boot dependency to 4.5.7

helm_deploy/values-staging.yaml
Updating staging ingress value to enable v1.2 and bring it in line with dev, preprod and prod.
Ensure we are not using deprecated Ingress APIs in any env.
=> Updating staging ingress value to enable v1.2

.trivyignore, build.gradle.kts
Updates to latest dependencies 
for latest fixes and updates
=> Prisoner-contact-registry - Update dependancies

build.gradle.kts
Update hmpps.gradle-spring-boot dependency to latest version.
Recommended fix for security failures.
=> Update hmpps.gradle-spring-boot dependency to latest version.

.trivyignore, build.gradle.kts
Dependencies update from 1.6.13 to 1.6.14
Standard dependencies update
to keep things uptodate
=> VB-1689 Update spring dependencies

Dockerfile
Update Dockerfile to add JRE 19 runtime
Update Dockerfile to add JRE 19 runtime
=> Dockerfile updates to add Java 19 runtime

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties
Updates dps-gradle-spring-boot dependencies.
Security fixes.
=> Update dps-gradle-spring-boot dependencies.

.circleci/config.yml, Dockerfile
Update JRE version to 20.
Update JRE version to 20.
=> Update JRE version to 20.

build.gradle.kts, helm_deploy/prisoner-contact-registry/Chart.yaml
Updates to helm chart versions for upgrading kubernetes to 1.25.
Updates to helm chart versions for upgrading kubernetes to 1.25.
=> Updates to helm chart versions for upgrading kubernetes to 1.25.

build.gradle.kts, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/helper/JwtAuthHelper.kt
Security updates.
Security updates.
=> Dependency updates as a fix for security issues and updates to JwtAuthHelper.kt to replace deprecated code.

helm_deploy/prisoner-contact-registry/values.yaml
remove serviceAccountName as not part of this change.
remove serviceAccountName as not part of this change.
=> VB-3115 - remove serviceAccountName as not part of this change.

.trivyignore, build.gradle.kts
Update dependencies.
Fix for security failures.
=> Update dependencies as a fix for security failures.

.circleci/config.yml, .trivyignore, Dockerfile, build.gradle.kts
Update dependencies as a fix for security failures and update circle-ci orb.
Updates dependencies and JDK upgrade
Security fixes
=> Update dependencies as a fix for security failures and update circle-ci orb.

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/client/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/controller/PrisonerContactController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/dto/ContactDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/dto/RestrictionDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/service/PrisonerContactRegistryService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/PrisonerContactControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/PrisonerGetSocialContactsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/mock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/service/PrisonerContactRegistryServiceTest.kt
Reverts back the existing endpoint as original and add a new endpoint to get only approved social visitors.
Public service.
=> Vb 3825 get contacts based on additional criteria

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/service/PrisonerContactRegistryService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/PrisonerContactControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/mock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/service/PrisonerContactRegistryServiceTest.kt
Just a small tidy up of tests, and hard coded json
to improve code quality
=> VB-3837 Tidy up of some of the tests in PCR

renovate.json
* Add renovate.json
* Update renovate initial pr to be in line with hmpps config
=> Configure Renovate (#104)

build.gradle.kts, gradle/wrapper/gradle-wrapper.properties, helm_deploy/prisoner-contact-registry/Chart.yaml, renovate.json, settings.gradle.kts
=> merge main into develop

.circleci/config.yml
We want to introduce trunk based feature development. To achieve this, we update the jobs to exclude deployment to preprod and prod from feature branches.
Also update config to allow main to automatically deploy to dev and staging.
=> Update circle ci pipeline for trunk based features

.trivyignore, build.gradle.kts
Upgrade to Kotlin 2.0 and spring boot 3.3.0
=> Upgrade to Kotlin 2.0 and spring boot 3.3.0

.circleci/config.yml
Update security pipeline to use latest jdk 21
=> Update security pipeline to use latest jdk 21

.circleci/config.yml
Allow optional deployment to either env for feature branches
=> Allow optional deployment to either env for feature branches

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/controller/PrisonerContactController.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/dto/VisitorActiveRestrictionsDto.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/service/PrisonerContactRegistryService.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/GetVisitorActiveRestrictionsPrisonerContactControllerTest.kt
This PR adds a new endpoint to return all active restrictions for a given approved social visitor.
https://dsdmoj.atlassian.net/browse/VB-3901
=> VB-3901 - Local visitor restrictions handled - new endpoint to get all active restrictions for visitor

.circleci/config.yml, .trivyignore, helm_deploy/prisoner-contact-registry/values.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-prod.yaml, helm_deploy/values-staging.yaml
Changed alert channels
Change alert channels
=> Move alert channels

.circleci/config.yml
Follow up ticket to reduce contexts.
VB-4523
=> VB-4523 - Update CircleCI contexts to reduce number of contexts.

src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/client/PrisonApiClient.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/controller/PrisonerContactControllerV2.kt, src/main/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/service/PrisonerContactRegistryServiceV2.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/IntegrationTestBase.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/PrisonerContactControllerTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/mock/PrisonApiMockServer.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/v2/GetDateRangeVisitorBannedRestrictionTypeTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/v2/GetVisitorClosedRestrictionTypeStatusTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/v2/PrisonerGetApprovedSocialContactsTest.kt, src/test/kotlin/uk/gov/justice/digital/hmpps/prisonercontactregistry/integration/v2/PrisonerGetSocialContactsTest.kt
New controller PrisonerContactControllerV2 and clean up endpoints to be the correct RESTful structure.
New service layer for new v2 controller.
Duplicate all tests to cover new controller / service.
https://dsdmoj.atlassian.net/browse/VB-4537
=> VB-4537 - V2 PrisonerContactController - Completely rework API layer

.circleci/config.yml
Updates Circle CI orb to version 10.
Update Circle CI orb to version 10.
=> Update Circle CI orb to version 10.

.circleci/config.yml
Updates Release channel
To update the release channel
=> Update Slack releases channel

helm_deploy/prisoner-contact-registry/values.yaml
Errors appeared after upgrading dps-spring-boot to 7.1.0. This is the fix
=> Fix application insights deserialisation errors
